name: Demo Workflow

on:
  push:
    branches:
      - main

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Display a success message
        run: echo "Welcome to GitHub Actions!"
      - name: Display the present working directory
        run: |
          pwd
          ls
