name: Sample Workflow
on: 
  push:
    branches:
      - main
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2
      - name: display a success message
        run: echo "Welcome to GitHub Actions!"
      - name: display the present working directory
        run: |
          pwd
          ls
